theme: jekyll-theme-slate

# Site settings
title: Samuel Gil
subtitle: Machine (Deep) Learning Craftsman
email: samuxiii@gmx.com
description: ""
baseurl: ""
url: "https://samuxiii.github.io"
linkedin_username: samuelgillopez
github_username:  samuxiii
